/**
 * Route-related types for CesiumPlaneFly
 * @packageDocumentation
 */

import type { Waypoint, WaypointInput } from './waypoint'

/**
 * Flight route configuration
 */
export interface RouteConfig {
  name?: string
  color?: string
  lineWidth?: number
}

/**
 * Flight route data structure
 */
export interface FlightRoute {
  id: string
  name: string
  waypoints: Waypoint[]
  color: string
  lineWidth: number
}

/**
 * Flight route input (without id, generated by system)
 */
export interface FlightRouteInput {
  name: string
  waypoints: WaypointInput[]
  color?: string
  lineWidth?: number
}

/**
 * Route data for store (internal use)
 */
export interface RouteData {
  id: string
  name: string
  waypoints: Waypoint[]
  color: string
  lineWidth: number
}

/**
 * Import result type
 */
export interface ImportResult {
  success: boolean
  errors: string[]
  importedCount?: number
}
